//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using Cross;
namespace GameFramework
{
    public class GMCommand
    {
        private static GMCommand m_gmcommand;
		private NetClient _netM;
        public GMCommand()
        {

        }
        public static GMCommand inst
        {
            get
            {
                if (m_gmcommand == null)
                {
                    m_gmcommand = new GMCommand();
                }
                return m_gmcommand;
            }
        }
		public void setNetManager( NetClient m )
		{
			_netM = m;
		}

		private void sendTPKG( uint cmd, Variant parm )
		{
			_netM.sendTpkg( cmd, parm );
		}
        public void get_item(string param)
        {
            Variant v1=new Variant();
            Variant v2 = new Variant();
            int blank = param.IndexOf(" ");
            string tpid = param.Substring(0, blank);
            string cnt = param.Substring(blank + 1);
            v2["tpid"] = int.Parse(tpid);
            v2["cnt"] = int.Parse(cnt);
            v1["cmd"] = "get_item";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void go_to(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            int blank = param.IndexOf(" ");
            string mapid = param.Substring(0, blank);
            int blank1 = param.IndexOf(" ", blank + 1);
            string x = param.Substring(blank + 1, blank1-blank-1);
            string y = param.Substring(blank1 + 1);
            v2["mpid"] = int.Parse(mapid);
            v2["x"] = int.Parse(x);
            v2["y"] = int.Parse(y);
            v1["cmd"] = "go_to";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void send_sys_mail(string param)
        {
            Variant v1 = new Variant();
            int blank = param.IndexOf(" ");
            string to_cid = param.Substring(0, blank);
            string data = param.Substring(blank + 1);
            // Variant par = JSON.parse(data);--------------------------------------------------------------------------------------------
           sendTPKG(50, v1);
        }
        public void acp_mis(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v2["id"] = int.Parse(param);
            v1["cmd"] = "acp_mis";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void fin_mis(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v2["id"] = int.Parse(param);
            v1["cmd"] = "fin_mis";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void speed(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v2["spd"] = int.Parse(param);
            v1["cmd"] = "speed";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void learn_skil(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v2["sid"] = int.Parse(param);
            v1["cmd"] = "learn_skil";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void active_meri(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v2["mid"] = int.Parse(param);
            v1["cmd"] = "active_meri";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void active_acup(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            int blank = param.IndexOf(" ");
            string mid = param.Substring(0, blank);
            string aid = param.Substring(blank + 1);
            v2["mid"] = int.Parse(mid);
            v2["aid"] = int.Parse(aid);
            v1["cmd"] = "active_acup";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void acup_up(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            int blank = param.IndexOf(" ");
            string mid = param.Substring(0, blank);
            string aid = param.Substring(blank + 1);
            v2["mid"] = int.Parse(mid);
            v2["mid"] = int.Parse(aid);
            v1["cmd"] = "acup_up";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void kick(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v2["name"] = int.Parse(param);
            v1["cmd"] = "kick";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void moveto(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v2["name"] = int.Parse(param);
            v1["cmd"] = "moveto";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void dragpl(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v2["name"] = int.Parse(param);
            v1["cmd"] = "dragpl";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void forb_talk(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            int blank = param.IndexOf(" ");
            string name = param.Substring(0, blank);
            string tm = param.Substring(blank + 1);
            v2["name"] = name;
            v2["tm"] = int.Parse(tm);
            v1["cmd"] = "forb_talk";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void seal_cha(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            int blank = param.IndexOf(" ");
            string name = param.Substring(0, blank);
            string tm = param.Substring(blank + 1);
            v2["name"] = name;
            v2["tm"] = int.Parse(tm);
            v1["cmd"] = "seal_cha";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void hide(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v1["cmd"] = "hide";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void add_npc(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            int blank = param.IndexOf(" ");
            string nid = param.Substring(0, blank);
            int blank1 = param.IndexOf(" ", blank + 1);
            string r = param.Substring(blank + 1, blank1-blank-1);
            string tm = param.Substring(blank1 + 1);
            v2["nid"] = int.Parse(nid);
            v2["r"] = int.Parse(r);
            v2["tm"] = int.Parse(tm);
            v1["cmd"] = "add_npc";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void add_mon(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            int blank = param.IndexOf(" ");
            string mid = param.Substring(0, blank);
            int blank1 = param.IndexOf(" ", blank + 1);
            string sdid = param.Substring(blank + 1, blank1-blank-1);
            int blank2 = param.IndexOf(" ", blank1 + 1);
            string r_x = param.Substring(blank1 + 1, blank2-blank1-1);
            int blank3 = param.IndexOf(" ", blank2 + 1);
            string r_y = param.Substring(blank2 + 1, blank3-blank2-1);
            string tm = param.Substring(blank3);
            v2["mid"] = int.Parse(mid);
            v2["sdid"] = int.Parse(sdid);
            v2["r_x"] = int.Parse(r_x);
            v2["r_y"] = int.Parse(r_y);
            v2["stm"] = int.Parse(tm);
            v1["cmd"] = "add_mon";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void broadcast(string param)
        {
            Variant v1 = new Variant();
            v1["tp"] = 6;
            v1["msg"] = param;
           sendTPKG(160, v1);
        }
        public void kill_mon(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            int blank = param.IndexOf(" ");
            string mid = param.Substring(0, blank);
            int blank1 = param.IndexOf(" ", blank + 1);
            string cnt = param.Substring(blank + 1, blank1-blank-1);
            string tm = param.Substring(blank1 + 1);
            v2["mid"] = int.Parse(mid);
            v2["cnt"] = int.Parse(cnt);
            v2["tm"] = int.Parse(tm);
            v1["cmd"] = "kill_mon";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void mod_pet_exp(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v2["exp"] = int.Parse(param);
            v1["cmd"] = "mod_pet_exp";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void set_ol_tms(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            int blank = param.IndexOf(" ");
            string ldol = param.Substring(0, blank);
            int blank1 = param.IndexOf(" ", blank + 1);
            string lwol = param.Substring(blank + 1, blank1-blank-1);
            string ofla = param.Substring(blank1 + 1);
            v2["ldol"] = int.Parse(ldol) * 3600;
            v2["lwol"] = int.Parse(lwol) * 3600;
            v2["ofla"] = int.Parse(ofla) * 3600;
            v1["cmd"] = "set_ol_tms";
            v1["par"]=v2;
           sendTPKG(50, v1);
        }
        public void set_vip(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v2["vip"] = int.Parse(param);
            v1["cmd"] = "set_vip";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void get_wh(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v2["tpid"] = int.Parse(param);
            v1["cmd"] = "get_wh";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void get_pet(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v2["tpid"] = int.Parse(param);
            v1["cmd"] = "get_pet";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void get_chpawd(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v2["id"] = int.Parse(param);
            v1["cmd"] = "get_chpawd";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void get_achive(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            int blank = param.IndexOf(" ");
            string achiveid = param.Substring(0, blank);
            string tm = param.Substring(blank + 1);
            v2["id"] = int.Parse(achiveid);
            v2["tm"] = int.Parse(tm);
            v1["cmd"] = "get_achive";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void del_achive(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            int blank = param.IndexOf(" ");
            if (blank >= 0)
            {
               
                string achiveid = param.Substring(0, blank);
                string cid = param.Substring(blank + 1);
                v2["id"] = int.Parse(achiveid);
                v2["cid"] = int.Parse(cid);
                v1["cmd"] = "del_achive";
                v1["par"] = v2;
               sendTPKG(50, v1);
            }
            else
            {
                v2["id"] = int.Parse(param);
                v1["cmd"] = "del_achive";
                v1["par"] = v2;
               sendTPKG(50, v1);
            }
        }
        public void set_fin_lvl(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            int blank = param.IndexOf(" ");
            string tpid = param.Substring(0, blank);
            int blank1 = param.IndexOf(" ", blank + 1);
            string diff = param.Substring(blank + 1, blank1-blank-1);
            string tm = param.Substring(blank1 + 1);
            v2["tpid"] = int.Parse(tpid);
            v2["diff"] = int.Parse(diff);
            v2["tm"] = int.Parse(tm);
            v1["cmd"] = "set_fin_lvl";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void set_carrlvl(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v2["lvl"] = int.Parse(param);
            v1["cmd"] = "set_carrlvl";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
        public void clr_cd(string param)
        {
            Variant v1 = new Variant();
            Variant v2 = new Variant();
            v2["cid"] = int.Parse(param);
            v1["cmd"] = "clr_cd";
            v1["par"] = v2;
           sendTPKG(50, v1);
        }
    }
}
